backend:
  name: github
  repo: victorldleon/decap-jekyll-template
  branch: master # Branch to update (main by default)

media_folder: "assets/img/uploads" # Folder where user uploaded files should go

collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }